//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spindox.AnagraficaDealer {
    
    
    public partial class DealerBusiness {
        
        /// <summary>
        /// ToolkitScriptManager1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.ToolkitScriptManager ToolkitScriptManager1;
        
        /// <summary>
        /// dealerBusinessUpdatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel dealerBusinessUpdatePanel;
        
        /// <summary>
        /// RelazioniSubMenuControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Spindox.AnagraficaDealer.UserControl.RelazioniSubMenuControl RelazioniSubMenuControl;
        
        /// <summary>
        /// GestioneDealerBusinessSubMenuControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Spindox.AnagraficaDealer.UserControl.GestioneDealerBusinessSubMenuControl GestioneDealerBusinessSubMenuControl;
        
        /// <summary>
        /// pnStudios control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnStudios;
        
        /// <summary>
        /// gvDealerBusiness control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView gvDealerBusiness;
        
        /// <summary>
        /// PopupModificheDealerBusiness control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Spindox.AnagraficaDealer.UserControl.RagioniSocialiCorrelate.PopupModificheDealerBusiness PopupModificheDealerBusiness;
        
        /// <summary>
        /// PopupAggiungiDealerBusiness control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Spindox.AnagraficaDealer.UserControl.RagioniSocialiCorrelate.PopupAggiungiDealerBusiness PopupAggiungiDealerBusiness;
        
        /// <summary>
        /// PopupMessaggio control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Spindox.AnagraficaDealer.UserControl.RagioniSocialiCorrelate.PopupMessaggio PopupMessaggio;
        
        /// <summary>
        /// PopupElimina control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Spindox.AnagraficaDealer.UserControl.RagioniSocialiCorrelate.PopupElimina PopupElimina;
    }
}
