//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spindox.AnagraficaDealer {
    
    
    public partial class ImportEccezioni {
        
        /// <summary>
        /// ToolkitScriptManager1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.ToolkitScriptManager ToolkitScriptManager1;
        
        /// <summary>
        /// importUpdatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel importUpdatePanel;
        
        /// <summary>
        /// AmministrazioneSubMenuControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Spindox.AnagraficaDealer.UserControl.AmministrazioneSubMenuControl AmministrazioneSubMenuControl;
        
        /// <summary>
        /// GestioneImportEccezioniSubMenuControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Spindox.AnagraficaDealer.UserControl.GestioneImportEccezioniSubMenuControl GestioneImportEccezioniSubMenuControl;
        
        /// <summary>
        /// eccImportGridView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView eccImportGridView;
        
        /// <summary>
        /// PopupAggiungiEccezione control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Spindox.AnagraficaDealer.UserControl.RagioniSocialiCorrelate.PopupAggiungiEccezione PopupAggiungiEccezione;
        
        /// <summary>
        /// PopupMessaggio control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Spindox.AnagraficaDealer.UserControl.RagioniSocialiCorrelate.PopupMessaggio PopupMessaggio;
        
        /// <summary>
        /// PopupElimina control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Spindox.AnagraficaDealer.UserControl.RagioniSocialiCorrelate.PopupElimina PopupElimina;
    }
}
